config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  resources :books do
    get 'delete', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :published_date, presence: { message: "can't be blank" }
  validate :published_date_cannot_be_in_future

  private

  def published_date_cannot_be_in_future
    if published_date.present? && published_date > Date.today
      errors.add(:published_date, "can't be in the future")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to books_path
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to books_path
    else
      render :edit
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book was successfully deleted."
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :price, :published_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_with(model: @book, local: true) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, step: :any %>
  </div>

  <div class="field">
    <%= form.label :published_date %>
    <%= form.date_select :published_date, 
                        start_year: Time.current.year - 100,
                        end_year: Time.current.year,
                        order: [:month, :day, :year] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back to Books', books_path %>

app/views/books/delete.html.erb
<h1>Delete Book</h1>

<p>Are you sure you want to delete the book "<%= @book.title %>"?</p>
<p>This action cannot be undone.</p>

<div>
  <%= button_to 'Delete Book', book_path(@book), method: :delete %> |
  <%= link_to 'Back to Books', books_path %>
</div>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<h1>Book Collection</h1>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Price</th>
      <th>Published Date</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= number_to_currency(book.price) %></td>
        <td><%= book.published_date.strftime("%B %-d, %Y") if book.published_date %></td>
        <td>
          <%= link_to 'Show', book_path(book) %> |
          <%= link_to 'Edit', edit_book_path(book) %> |
          <%= link_to 'Delete', delete_book_path(book) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Book', new_book_path %>

app/views/books/new.html.erb
<h1>Add a New Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<h1>Book Details</h1>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@book.price) %>
</p>

<p>
  <strong>Published Date:</strong>
  <%= @book.published_date.strftime("%B %-d, %Y") if @book.published_date %>
</p>

<%= link_to 'Back to Books', books_path %> |
<%= link_to 'Edit', edit_book_path(@book) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="flash-message <%= name %>">
          <%= msg %>
          <button class="close-button" onclick="this.parentElement.style.display='none'">×</button>
        </div>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>